from django.urls import path
from .views import (
    AddressDetailView,
    AddressListCreateView,
    AuthTokenView,
    AuthTokenRefreshView,
    CartItemDetailView,
    CartView,
    CategoryListCreateView,
    CsrfView,
    ConsultationView,
    HealthView,
    LogoutView,
    OrderListCreateView,
    OrderStatusView,
    OrdersAdminView,
    OrderPaymentView,
    OrderCancelView,
    OrderDeleteView,
    ProductListCreateView,
    ProductDetailView,
    PriceListView,
    ProductVariantListCreateView,
    ProductVariantDetailView,
    ProfileView,
    RegisterView,
    MeView,
)

urlpatterns = [
    path('health/', HealthView.as_view(), name='health'),
    path('auth/csrf/', CsrfView.as_view(), name='csrf'),
    path('auth/register/', RegisterView.as_view(), name='register'),
    path('auth/token/', AuthTokenView.as_view(), name='token_obtain_pair'),
    path('auth/token/refresh/', AuthTokenRefreshView.as_view(), name='token_refresh'),
    path('auth/logout/', LogoutView.as_view(), name='logout'),
    path('consultation/', ConsultationView.as_view(), name='consultation'),
    path('account/me/', MeView.as_view(), name='account-me'),
    path('account/profile/', ProfileView.as_view(), name='profile'),
    path('account/addresses/', AddressListCreateView.as_view(), name='addresses'),
    path('account/addresses/<int:pk>/', AddressDetailView.as_view(), name='address-detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('cart/items/<int:item_id>/', CartItemDetailView.as_view(), name='cart-item'),
    path('orders/', OrderListCreateView.as_view(), name='orders'),
    path('orders/admin/', OrdersAdminView.as_view(), name='orders-admin'),
    path('orders/<int:order_id>/', OrderDeleteView.as_view(), name='order-delete'),
    path('orders/<int:order_id>/pay/', OrderPaymentView.as_view(), name='order-pay'),
    path('orders/<int:order_id>/status/', OrderStatusView.as_view(), name='order-status'),
    path('orders/<int:order_id>/cancel/', OrderCancelView.as_view(), name='order-cancel'),
    path('catalog/categories/', CategoryListCreateView.as_view(), name='categories'),
    path('catalog/pricelist/', PriceListView.as_view(), name='pricelist'),
    path('catalog/products/', ProductListCreateView.as_view(), name='products'),
    path('catalog/products/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('catalog/products/<int:product_id>/variants/', ProductVariantListCreateView.as_view(), name='product-variants'),
    path('catalog/variants/<int:pk>/', ProductVariantDetailView.as_view(), name='variant-detail'),
]
